In [1]:
import os
from dotenv import load_dotenv
import requests
import pandas as pd
import matplotlib as plt
import json
from fredapi import Fred

In [2]:
load_dotenv()
fred_api_key = os.getenv("FRED_API_KEY")
fred = Fred(api_key=fred_api_key)

In [72]:
df_rpp = fred.search('Regional Price Parities: All Items')
# df_inc = df_inc.query('units == ""')

df_rpp = df_rpp.loc[df_rpp['title'].str.contains('Regional Price Parities: All Items for')]

In [73]:
df_rpp.shape

(432, 15)

In [74]:
df_rpp.tail()

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,notes
series id,,,,,,,,,,,,,,,
RPPALL19780,RPPALL19780,2024-01-30,2024-01-30,Regional Price Parities: All Items for Des Moi...,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:59:58-06:00,0,Regional price parities (RPPs) are regional pr...
RPPALL37860,RPPALL37860,2024-01-30,2024-01-30,Regional Price Parities: All Items for Pensaco...,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:59:56-06:00,0,Regional price parities (RPPs) are regional pr...
RPPALL14860,RPPALL14860,2024-01-30,2024-01-30,Regional Price Parities: All Items for Bridgep...,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:59:59-06:00,0,Regional price parities (RPPs) are regional pr...
RPPALL15540,RPPALL15540,2024-01-30,2024-01-30,Regional Price Parities: All Items for Burling...,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:59:59-06:00,0,Regional price parities (RPPs) are regional pr...
RPPALL10900,RPPALL10900,2024-01-30,2024-01-30,Regional Price Parities: All Items for Allento...,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:59:59-06:00,0,Regional price parities (RPPs) are regional pr...

In [75]:
rpp_result = df_rpp[~df_rpp['title'].str.endswith('(MSA)')]

In [76]:
rpp_result.shape

(51, 15)

In [77]:
all_states = [
    'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA',
    'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK',
    'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
]

# Convert your series index to a list
existing_states = list(rpp_result.index.str[:2])

# Find the missing states
missing_states = set(all_states) - set(existing_states)

# Display the missing states
print("Missing States:", missing_states)

Missing States: set()

In [78]:
rpp_result['title']

series id
MIRPPALL      Regional Price Parities: All Items for Michigan
NMRPPALL    Regional Price Parities: All Items for New Mexico
TXRPPALL         Regional Price Parities: All Items for Texas
FLRPPALL       Regional Price Parities: All Items for Florida
IARPPALL          Regional Price Parities: All Items for Iowa
ALRPPALL       Regional Price Parities: All Items for Alabama
ILRPPALL      Regional Price Parities: All Items for Illinois
INRPPALL       Regional Price Parities: All Items for Indiana
ARRPPALL      Regional Price Parities: All Items for Arkansas
NVRPPALL        Regional Price Parities: All Items for Nevada
KSRPPALL        Regional Price Parities: All Items for Kansas
MDRPPALL      Regional Price Parities: All Items for Maryland
CORPPALL      Regional Price Parities: All Items for Colorado
MNRPPALL     Regional Price Parities: All Items for Minnesota
MSRPPALL    Regional Price Parities: All Items for Mississ...
UTRPPALL          Regional Price Parities: All Items for Utah
VTRPPALL       Regional Price Parities: All Items for Vermont
HIRPPALL        Regional Price Parities: All Items for Hawaii
WVRPPALL    Regional Price Parities: All Items for West Vi...
WYRPPALL       Regional Price Parities: All Items for Wyoming
NYRPPALL      Regional Price Parities: All Items for New York
SDRPPALL    Regional Price Parities: All Items for South D...
CARPPALL    Regional Price Parities: All Items for California
AZRPPALL       Regional Price Parities: All Items for Arizona
OKRPPALL      Regional Price Parities: All Items for Oklahoma
WARPPALL    Regional Price Parities: All Items for Washington
DERPPALL      Regional Price Parities: All Items for Delaware
ORRPPALL        Regional Price Parities: All Items for Oregon
IDRPPALL         Regional Price Parities: All Items for Idaho
TNRPPALL     Regional Price Parities: All Items for Tennessee
AKRPPALL        Regional Price Parities: All Items for Alaska
OHRPPALL          Regional Price Parities: All Items for Ohio
MERPPALL         Regional Price Parities: All Items for Maine
NHRPPALL    Regional Price Parities: All Items for New Ham...
NDRPPALL    Regional Price Parities: All Items for North D...
PARPPALL    Regional Price Parities: All Items for Pennsyl...
NCRPPALL    Regional Price Parities: All Items for North C...
LARPPALL     Regional Price Parities: All Items for Louisiana
KYRPPALL      Regional Price Parities: All Items for Kentucky
MORPPALL      Regional Price Parities: All Items for Missouri
NERPPALL      Regional Price Parities: All Items for Nebraska
NJRPPALL    Regional Price Parities: All Items for New Jersey
MARPPALL    Regional Price Parities: All Items for Massach...
DCRPPALL    Regional Price Parities: All Items for Distric...
GARPPALL       Regional Price Parities: All Items for Georgia
CTRPPALL    Regional Price Parities: All Items for Connect...
WIRPPALL     Regional Price Parities: All Items for Wisconsin
MTRPPALL       Regional Price Parities: All Items for Montana
VARPPALL      Regional Price Parities: All Items for Virginia
RIRPPALL    Regional Price Parities: All Items for Rhode I...
SCRPPALL    Regional Price Parities: All Items for South C...
Name: title, dtype: object

In [80]:
rpp_result.tail()

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,notes
series id,,,,,,,,,,,,,,,
WIRPPALL,WIRPPALL,2024-01-30,2024-01-30,Regional Price Parities: All Items for Wisconsin,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:56:41-06:00,1,Regional price parities (RPPs) are regional pr...
MTRPPALL,MTRPPALL,2024-01-30,2024-01-30,Regional Price Parities: All Items for Montana,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:59:15-06:00,1,Regional price parities (RPPs) are regional pr...
VARPPALL,VARPPALL,2024-01-30,2024-01-30,Regional Price Parities: All Items for Virginia,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 12:00:34-06:00,0,Regional price parities (RPPs) are regional pr...
RIRPPALL,RIRPPALL,2024-01-30,2024-01-30,Regional Price Parities: All Items for Rhode I...,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 11:59:46-06:00,0,Regional price parities (RPPs) are regional pr...
SCRPPALL,SCRPPALL,2024-01-30,2024-01-30,Regional Price Parities: All Items for South C...,2008-01-01,2022-01-01,Annual,A,Index,Index,Not Seasonally Adjusted,NSA,2023-12-14 12:00:36-06:00,0,Regional price parities (RPPs) are regional pr...

In [81]:
all_result =[]

for id in rpp_result.index:
    result = fred.get_series(id)
    result = result.to_frame(name = id)
    all_result.append(result)

In [82]:
all_result[1]

            NMRPPALL
2008-01-01    95.114
2009-01-01    95.964
2010-01-01    94.505
2011-01-01    97.088
2012-01-01    96.483
2013-01-01    95.561
2014-01-01    95.469
2015-01-01    95.414
2016-01-01    94.452
2017-01-01    95.720
2018-01-01    91.625
2019-01-01    92.967
2020-01-01    91.790
2021-01-01    89.812
2022-01-01    90.981

In [83]:
rpp_state = pd.concat(all_result, axis=1)

In [84]:
rpp_state.tail()

,MIRPPALL,NMRPPALL,TXRPPALL,FLRPPALL,IARPPALL,ALRPPALL,ILRPPALL,INRPPALL,ARRPPALL,NVRPPALL,...,NJRPPALL,MARPPALL,DCRPPALL,GARPPALL,CTRPPALL,WIRPPALL,MTRPPALL,VARPPALL,RIRPPALL,SCRPPALL
2018-01-01,94.458,91.625,97.745,100.315,91.841,87.388,100.323,92.737,87.156,96.198,...,111.078,107.264,111.510,94.819,104.057,93.951,92.371,102.018,102.076,92.261
2019-01-01,95.309,92.967,98.444,99.701,91.873,88.326,99.385,92.790,87.730,98.845,...,111.253,107.011,109.247,94.384,103.877,94.430,94.244,100.108,102.346,91.531
2020-01-01,94.413,91.790,98.807,100.580,90.767,87.581,100.289,91.755,88.228,97.184,...,110.711,109.014,110.895,94.491,105.118,92.647,91.921,101.026,101.793,90.889
2021-01-01,94.193,89.812,98.421,101.409,89.778,88.026,101.262,92.496,88.927,95.409,...,109.223,106.626,111.658,95.748,102.751,93.220,91.385,102.329,102.083,93.637
2022-01-01,93.428,90.981,97.512,102.144,88.422,87.776,101.257,91.817,86.597,96.383,...,108.757,109.393,112.847,95.832,106.412,92.310,90.266,102.137,104.700,93.551

In [85]:
id_to_state = df_rpp['title'].str.replace('Regional Price Parities: All Items for ','').to_dict()

In [86]:
rpp_state.columns = [id_to_state[d] for d in rpp_state.columns]

In [87]:
rpp_state.columns

Index(['Michigan', 'New Mexico', 'Texas', 'Florida', 'Iowa', 'Alabama',
       'Illinois', 'Indiana', 'Arkansas', 'Nevada', 'Kansas', 'Maryland',
       'Colorado', 'Minnesota', 'Mississippi', 'Utah', 'Vermont', 'Hawaii',
       'West Virginia', 'Wyoming', 'New York', 'South Dakota', 'California',
       'Arizona', 'Oklahoma', 'Washington', 'Delaware', 'Oregon', 'Idaho',
       'Tennessee', 'Alaska', 'Ohio', 'Maine', 'New Hampshire', 'North Dakota',
       'Pennsylvania', 'North Carolina', 'Louisiana', 'Kentucky', 'Missouri',
       'Nebraska', 'New Jersey', 'Massachusetts', 'District of Columbia',
       'Georgia', 'Connecticut', 'Wisconsin', 'Montana', 'Virginia',
       'Rhode Island', 'South Carolina'],
      dtype='object')

In [88]:
rpp_state.tail()

,Michigan,New Mexico,Texas,Florida,Iowa,Alabama,Illinois,Indiana,Arkansas,Nevada,...,New Jersey,Massachusetts,District of Columbia,Georgia,Connecticut,Wisconsin,Montana,Virginia,Rhode Island,South Carolina
2018-01-01,94.458,91.625,97.745,100.315,91.841,87.388,100.323,92.737,87.156,96.198,...,111.078,107.264,111.510,94.819,104.057,93.951,92.371,102.018,102.076,92.261
2019-01-01,95.309,92.967,98.444,99.701,91.873,88.326,99.385,92.790,87.730,98.845,...,111.253,107.011,109.247,94.384,103.877,94.430,94.244,100.108,102.346,91.531
2020-01-01,94.413,91.790,98.807,100.580,90.767,87.581,100.289,91.755,88.228,97.184,...,110.711,109.014,110.895,94.491,105.118,92.647,91.921,101.026,101.793,90.889
2021-01-01,94.193,89.812,98.421,101.409,89.778,88.026,101.262,92.496,88.927,95.409,...,109.223,106.626,111.658,95.748,102.751,93.220,91.385,102.329,102.083,93.637
2022-01-01,93.428,90.981,97.512,102.144,88.422,87.776,101.257,91.817,86.597,96.383,...,108.757,109.393,112.847,95.832,106.412,92.310,90.266,102.137,104.700,93.551

In [ ]:
# export unemp_state to csv
rpp_state.to_csv('../cleansed data/state_rpp.csv')